# select the needed variables
## ssies3
ssies3_vars = [
    "Epoch",
    "glat",
    "glon",
    "alt",
    "vx",
    "vxqual",
    "vy",
    "vyqual",
    "vz",
    "vzqual",
    "temp",
    "tempqual",
    "frach",
    "frachqual",
    "frache",
    "frachequal",
    "fraco",
    "fracoqual",
    "bx",
    "by",
    "bz",
    "ductdens",
    "te",
]  # if the info are duplicated, just use one payload (except 'Epoch').
## ssm
ssm_vars = [
    "Epoch",
    "SC_GEOCENTRIC_LAT",
    "SC_GEOCENTRIC_LON",
    "SC_GEOCENTRIC_R",
    "SC_AACGM_LAT",
    "SC_AACGM_LON",
    "SC_AACGM_LTIME",
    "B_SC_OBS_ORIG",
    "DELTA_B_GEO",
    "DELTA_B_SC",
    "SC_ALONG_GEO",
    "AURORAL_REGION",
    "ORBIT_INDEX",
    "AURORAL_BOUNDARY_FOM",
    "SC_ACROSS_GEO",
]