fgm_vars = (
        "A221",
        "A222",
        "A223",
        "ALTITUDE",
        "B_FGM1",
        "B_FGM2",
        "B_FGM3",
        "FLAG_MT",
        "FLAG_SHW",
        "FLAG_TBB",
        "GEO_LAT",
        "GEO_LON",
        "MAG_LAT",
        "MAG_LON",
        "UTC_TIME",
        "VERSE_TIME",
    )
scm_ulf_vars = (
    "A231_P",
    "A231_W",
    "A232_P",
    "A232_W",
    "A233_P",
    "A233_W",
    "ALTITUDE",
    "FLAG",
    "FREQ",
    "GEO_LAT",
    "GEO_LON",
    "MAG_LAT",
    "MAG_LON",
    "PhaseX",
    "PhaseY",
    "PhaseZ",
    "UTC_TIME",
    "VERSE_TIME",
    "WORKMODE",
)
scm_ulf_1c_vars = (
    "ALTITUDE",
    "FLAG",
    "GEO_LAT",
    "GEO_LON",
    "MAG_LAT",
    "MAG_LON",
    "UTC_TIME",
    "VERSE_TIME",
    "WORKMODE",
)
scm_ulf_resample_vars = ["A231_W", "A232_W", "A233_W"]
efd_ulf_vars = (
    "A111_P",
    "A111_W",
    "A112_P",
    "A112_W",
    "A113_P",
    "A113_W",
    "ALTITUDE",
    "FREQ",
    "GEO_LAT",
    "GEO_LON",
    "MAG_LAT",
    "MAG_LON",
    "UTC_TIME",
    "VERSE_TIME",
    "WORKMODE",
)
efd_ulf_1c_vars = (
    "ALTITUDE",
    "GEO_LAT",
    "GEO_LON",
    "MAG_LAT",
    "MAG_LON",
    "UTC_TIME",
    "VERSE_TIME",
    "WORKMODE",
)
efd_ulf_resample_vars = ["A111_W", "A112_W", "A113_W"]
scmulf_fs = 1024
efdulf_fs = 125